apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
    - port: 6379
  selector:
    app: redis


---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  ports:
    - port: 8080
  selector:
    app: url-shortener


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Expose on Minikube
  selector:
    app: nginx