services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - api_gateway_network

  url_shortener:
    build:
      context: ../
      dockerfile: ./ci/Dockerfile_app
    networks:
      - api_gateway_network
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    networks:
      - api_gateway_network
    ports:
      - "80:80"
    depends_on:
      - url_shortener

volumes:
  redis_data:

networks:
  api_gateway_network: